server:
  port: 8084

#spring:
 # datasource:
 #   url: jdbc:mysql://prod-db-cluster:3306/demo_db



#server:
#  port: 8089
#spring:
 # datasource:
  #  url: jdbc:mysql://prod-db-cluster:3306/demo_db
#logging:
 # level:
  #  com.example.order: INFO
#external:
 # payment:
  #  url: https://api.payment.prod.com/process
#spring:
 # config:
  #  import: optional:configserver:
   # default-label: main

#common:
 # message: "Shared configuration for all microservices"
